SimEngineLightVEXMixin: Don't default to fail
  * Current: If no `block` is passed, it defaults to `None`, and breaks the
assertion;
  * New: If no `block` is passed, then there is an exception raised
  corresponding to the missing parameter.
```
cat << __EOF__ > test_issue.py
from angr.engines.light import SimEngineLightVEXMixin

class Engine(SimEngineLightVEXMixin):
    def __init__(self):
        pass

engine = Engine()
engine._process('state', 'successors')
__EOF__

python test_issue.py
```

Triggers:
> TypeError: _process() missing 1 required keyword-only argument: 'block'

Signed-off-by: Pamplemousse <xav.maso@gmail.com>