Miscellaneous small corrections (#2436)
* `CodeLocation`: Correct string representation

`.context` is a tuple!

Signed-off-by: Pamplemousse <xav.maso@gmail.com>

* ForwardAnalysis: Match error message with method name

Signed-off-by: Pamplemousse <xav.maso@gmail.com>

* RDA: Correct representation of `CallTrace`

Signed-off-by: Pamplemousse <xav.maso@gmail.com>

* engines.light.SpOffset: Explicit that offset is in hex

Signed-off-by: Pamplemousse <xav.maso@gmail.com>

* SimEngineLightVEXMixin: Don't default to fail

  * Current: If no `block` is passed, it defaults to `None`, and breaks the
assertion;
  * New: If no `block` is passed, then there is an exception raised
  corresponding to the missing parameter.
```
cat << __EOF__ > test_issue.py
from angr.engines.light import SimEngineLightVEXMixin

class Engine(SimEngineLightVEXMixin):
    def __init__(self):
        pass

engine = Engine()
engine._process('state', 'successors')
__EOF__

python test_issue.py
```

Triggers:
> TypeError: _process() missing 1 required keyword-only argument: 'block'

Signed-off-by: Pamplemousse <xav.maso@gmail.com>